FROM alpine:latest

# Runtime arguments
ARG APP_DIR=/app
ARG BUILD_DATE
ARG IMAGE_NAME
ARG MAINTAINER
ARG SRC_DIR=.

# Container Labels
LABEL maintainer=$MAINTAINER
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.build-date=$BUILD_DATE
LABEL org.label-schema.name=$IMAGE_NAME
LABEL org.label-schema.version=$BUILD_VERSION
